name: Generate Snake Animation

on:
  schedule:
    - cron: "0 7,11,17 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: mas663
          outputs: dist/snake.svg

      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate Snake Animation"
          add: "dist/snake.svg"
